# .github/workflows/deploy.yml
name: Déploiement sur o2switch

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Synchro FTP/FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server:                 ${{ secrets.SFTP_HOST }}
          username:               ${{ secrets.SFTP_USERNAME }}
          password:               ${{ secrets.SFTP_PASSWORD }}
          protocol:               ftp               # ou 'ftps' si votre hébergeur supporte FTPS
          port:                   21                # ou port FTPS (généralement 21 ou 990)
          local-dir:              ./                # dossier local à envoyer
          server-dir:             public_html/      # dossier cible côté serveur
          dangerous-clean-slate:  true              # supprime les fichiers distants obsolètes
