# .github/workflows/main.yml
name: Déploiement sur o2switch

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Synchro FTP/FTPS (dry-run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:                ${{ secrets.SFTP_HOST }}
          username:              ${{ secrets.SFTP_USERNAME }}
          password:              ${{ secrets.SFTP_PASSWORD }}
          protocol:              ftp
          port:                  21
          local-dir:             site/             # votre dossier de site
          server-dir:            public_html/      # ou ./ si public_html est votre racine FTP
          dangerous-clean-slate: false             # pas de purge complète
          dry-run:               true              # simule seulement
